[project]
name = "i2iwfilm"
version = "1.0.0"
dependencies = [
    "numpy==1.26.4",
    "sunpy==5.1.3",
    "pytorch_lightning",
    "omegaconf",
    "hydra-core",
    "matplotlib",
    "tqdm",
    "scikit-learn",
    "scikit-image",
    "pandas",
    "opencv-python",
    "itkwidgets",
    "torchvision",
    "torchmetrics",
    "mlflow",
    "wandb",
    "nibabel",
    "SimpleITK",
    "monai",
    "albumentations==1.3.1",
    "kornia",
    "einops",
    "k3d",
    "vtk",
    "seaborn",
    "configparser",
    "ipywidgets",
    "scipy",
    "cachetools",
    "shapely",
    "pymysql",
    "jupyter",
]

[tool.setuptools.packages.find]
# All the following settings are optional:
include = ["i2iwfilm"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
